name: floodwatch
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26
  - pandas=2.2
  - xarray=2024.06
  - dask=2024.06
  - rasterio=1.3.9
  - rioxarray=0.15.5
  - shapely=2.0.4
  - pyproj=3.6.1
  - geopandas=0.14.4
  - pystac-client=0.8.3
  - stackstac=0.5.0
  - planetary-computer=1.0.0
  - pip:
      - streamlit==1.36.0
      - pydeck==0.9.1
      - tqdm==4.66.4
